name: home_beacon
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cloud_firestore: ^3.1.0
  firebase_auth: ^3.2.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^0.15.0
  google_sign_in: ^5.2.1
  json_annotation: ^4.3.0
  sign_in_with_apple: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^0.15.1+1
  flutter_lints: ^1.0.0
  build_runner: ^2.1.5
  json_serializable: ^6.0.1

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
